# Generated by Django 3.2 on 2021-06-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Назва бренда', max_length=100)),
                ('image', models.ImageField(upload_to='logo/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Логотип',
                'verbose_name_plural': 'Логотипи',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Група товара', max_length=250)),
                ('ukr_name', models.CharField(help_text='Група товара на українській мові', max_length=250)),
                ('article', models.CharField(help_text='Артикул', max_length=250)),
                ('product_code', models.CharField(help_text='Скорочений артикул', max_length=250)),
                ('color_name', models.CharField(help_text='Назва кольору', max_length=250)),
                ('color_code', models.CharField(help_text='Код кольору', max_length=100)),
                ('img_link', models.URLField()),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
    ]
