# Generated by Django 3.2 on 2021-06-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UksImageSearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='svg_code',
            field=models.TextField(default='', verbose_name='Код svg'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(upload_to='logo/', verbose_name='Изображение логотипа'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название бренда'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(max_length=250, verbose_name='Полный артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_code',
            field=models.CharField(max_length=100, verbose_name='Код цвета'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_name',
            field=models.CharField(max_length=250, verbose_name='Название цвета'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_link',
            field=models.URLField(verbose_name='Сылка на изображения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Група товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=250, verbose_name='Сокращеный артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ukr_name',
            field=models.CharField(max_length=250, verbose_name='Група товара Укр.'),
        ),
    ]
